### ISSUE TITLE
MenuBar, fixed or not?

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaWeb#18]
When I first moved the site to bootstrap the fixed MenuBar at the top seemed interesting.
- Will this work on all browsers?
- Should the menu (can it?) be fixed on small devices but not on desktops?
- The left side "logo" and "Home" item do the same thing, should one be eliminated?
- Should "Browse" and "Search" be combined somehow?

Working on this issue should include prototype images (small and large format devices) and discussion.

**Comment by ksnortum** [comment]
> The left side "logo" and "Home" item do the same thing, should one be eliminated?

I think it's fairly common to have both these functions.  If we ever have a page without the menubar, the "go home on icon" feature will be needed.

**Comment by PaulMorris** [comment]
I don't have a strong view on fixed vs unfixed menu bar.  I would expect the fixed menu to work on all recent browsers (if bootstrap is doing its job).  If it's not fixed we should provide footer navigation, so maybe it's simpler to go with fixed.

> The left side "logo" and "Home" item do the same thing, should one be eliminated?

My suggestion would be to replace both of these with a single "Mutopia" or "Mutopia Project" or "The Mutopia Project" link/item.  (Maybe in the blue color and utopia font?)  Since we're not a big brand with a recognizable logo, better to go with our name.

> Should "Browse" and "Search" be combined somehow?

Maybe...  but I wonder if it would make sense to postpone such changes until after the new site is up?  So launch the new site with a version that basically replicates the old site, and then go on to do further changes.  That would simplify things into smaller steps and make for a quicker transition to the new site.

For example, I was thinking that the "In Process" page could just become a wiki page on github that we link to from the "Contributing" page.  That would allow for easier maintenance of that list.  But that wouldn't need to happen (if it happens at all...) before the transition to the new site.

Maybe we could have a label "post-html5-launch" for such deferred issues, or better yet, have a label for "html5-launch" issues that need to be resolved before the launch?

**Comment by glenl** [comment]
Your idea for the "In Process" page is noted. We still have email contributors but you don't need a user account to view the wiki.

Old site: Home, Browse the Archive, Advanced Search, ...
New : Home, Browse, Search

The problem is that Browse and Search are almost synonyms. Another topic and perhaps one for its own issue as well.

It looks like the fixed menu is generally accepted so let's continue testing with that.
 @ksnortum - I want to have a menubar on every page.
