### ISSUE TITLE
Advanced search page rework

### ISSUE THREAD

**Issue by glenl** [MutopiaProject/MutopiaWeb#57]
I think we have some opportunities with HTML5, bootstrap, and form groups to improve the usability of the advanced search page. This task may drive a new advanced search look in prototype 3 but is mostly about starting a discussion about presentation consistency in web search forms.

On "no discussion" I will close this issue for prototype 3 with no changes to this page.

**Comment by ksnortum** [comment]
I'd hate for this to close without discussion.  I'm probably not the guy to do it, though.  I'm mostly a backend kinda guy.

**Comment by glenl** [comment]
I've done a basic HTML5 rework using some bootstrap components in issue #64. I went ahead and merged the work so it is now in the main branch but it is still a work in progress. I would like to get feedback from those who are following this issue but aren't building the prototype site while it is in progress, I've attached the current image of the search panel.
![shot-2015-12-28_09-08-24](https://cloud.githubusercontent.com/assets/2857841/12022263/01cc5b72-ad43-11e5-8cd5-10905a128dc9.jpg)
Because "include preview images" is now a check-box and clearly associated with the submit button, I've chosen to remove the textual directives we had before. The numeric selector will not allow a number < 1.

**Comment by ksnortum** [comment]
It looks great.

**Comment by dominicus** [comment]
I like this layout much more.  Improved intuitiveness.
- On the top search keyword field, the hint reads "Search for...".  Consider alternative "keywords to search for ..."
- Consider "Search" instead of "Submit" for the bottom button.
- Will pressing the search icon on the keyword box be equivalent to pressing the bottom "Submit" button?
- Consider placing icon on the right side for consistency with other search boxes.
- Consider "include preview images in search results", or "show preview images in results"

I noticed some unexpected behavior on the "advanced search" page at the published prototype site.
- I get expected output for several composers I tried, but a keyword search for "bach" or selecting "J.S. Bach" from the composer pull-down yields zero results.  Similar issue if I search for instrument="Organ".
- In a search with multi-page results, if I choose to include preview images, these will display only on the first batch of 10 results.  Hitting "next 10" will not include preview images.
- The titles for search results "Music Listing - with preview images" or "Music Listing - without preview images" could be re-worded.  I would drop the "with/without image warning".  I'm guessing the intent of adding the "- without preview images" warning is to make the user aware that showing previews is possible...in case they didn't read through all the advanced options.  Maybe more productive than a warning could be adding a button at top where the user can toggle "show preview images"/"hide preview images" while reviewing results.  Preview images are a welcome feature for those who can quickly sight-read music.

Other/wishful:
- For multi-page results, a subtitle or right-aligned indication of which page is currently displayed (e.g. "results 21-30")?
- An option in advanced search to request pieces _added_ in the last X weeks (choice to include or exclude updates).  Maybe this is a feature best tackled when there's a running database?
- Would be nice to have a link at the top of search results to "refine search".  This would show the Advanced Search screen with the previously applied search terms. As it is right now, the only way to refine an existing search while on page X is to hit back-button however many pages you may be into the results.

**Comment by glenl** [comment]
Some quick notes on @dominicus's comment:
- The search icon is not a button, just an icon. Typically, buttons on entry boxes go on the right but I agree this is confusing.
- It is possible to have multiple controls (magnifier glyph as a button, "Search" button, carriage return) but it introduces some confusion: does pressing a search button on a text entry box do something different than pressing a "Search" button at the bottom of the panel? That is, does it only do a keyword search and ignore the options below it? The magnifier glyph is cute but not necessary on a big search panel; an alternative is to put the glyph left-aligned within the text entry box along with the place-holder text.

The unexpected results are because the proto site is not a fully populated site. On the next prototype publication I'll see if Chris can connect this up to the main archive.
- _Added vs. updated in the last X weeks/days_ is an interesting feature and we might be able to come up with a reasonable method with the current data back-end. I may add this as a separate feature.
- _Feature to add images to a search to an existing search page_ is a great idea. I'll add that as an issue as well.

Your text treatment has been noted! Good feedback.

**Comment by dominicus** [comment]
_does pressing a search button on a text entry box do something different than pressing a "Search" button at the bottom of the panel?_
I would expect a click on search button or bottom button, or pressing [Enter], incorporates all criteria as shown.  This is the behavior implemented on the legacy page.
The advanced search parameters default come with all-inclusive bias, so any parameter updates from default values is fair to assume a deliberate action by the visitor to narrow results.
